### ISSUE TITLE
Please add auto reconnection 

### ISSUE THREAD

**Issue by Arek-Arek** [xavery/czateria#8] opened 2020-01-05 10:52 UTC
After couple of hours czateria closes websocket. Maybe it would be easy to add support for automatic recconection? Especially for registered nick.

```sty 05 03:52:39 debug unknown:0 unknown {"code":1003}
sty 05 03:53:19 debug unknown:0 unknown {"code":1003}
sty 05 03:53:59 debug unknown:0 unknown {"code":1003}
sty 05 03:54:13 info unknown:0 unknown Socket error QAbstractSocket::RemoteHostClosedError "The TLS/SSL connection has been closed"
sty 05 03:54:13 debug unknown:0 unknown {"code":33}
sty 05 03:54:13 info unknown:0 unknown Unhandled WebSocket message :
sty 05 03:54:13  {"code":33}
sty 05 03:54:13 info unknown:0 unknown Socket error QAbstractSocket::RemoteHostClosedError "The remote host closed the connection"
sty 05 03:54:39 debug unknown:0 unknown {"code":1003}
sty 05 03:55:19 debug unknown:0 unknown {"code":1003}
sty 05 03:55:59 debug unknown:0 unknown {"code":1003}
sty 05 03:56:39 debug unknown:0 unknown {"code":1003}
```

**Comment by Arek-Arek** [comment] 2020-01-05 11:04
I think this is not bug but a enhancement :)

**Comment by xavery** [comment] 2020-01-05 11:06
Sounds like a bug to me - after all, it's normal to expect network applications to automatically reconnect when losing connectivity. :)
I have to admit I have never kept the program running so long for the server to break the connection. Shouldn't be that hard to reproduce and fix, hopefully.

**Comment by Arek-Arek** [comment] 2020-01-05 11:10
This happened after about 7-8 hours of connecting. The same happens on browser. I think Interia does it to cut hanging session.

**Comment by xavery** [comment] 2020-01-06 11:10
Doesn't look like this can be done automatically for anonymous logins. I modified the code to reconnect to the server and re-send the login request as it was previously sent. The server replied with a code 150, subcode 25 message, which appears to be a kind of a "logout request" to the client.
The reason behind this is probably the sessionId which is embedded into the login request - when its validity (which actually appears to be ~8 hours) ends, the server removes the session and denies any further login requests with this ID. The session ID is obtained by sending a login request to a separate server, which then asks the client to solve the captcha for anonymous logins.

**Comment by xavery** [comment] 2020-01-08 19:06
Should be solved by #15 , merged in 9be7087f0a026cbd7e839544e79f97d96fb8874a - like described, only for registered nicks due to captchas not being needed.

**Closed by xavery** 2020-01-08 19:06 UTC
Labels: bug

**Comment by Arek-Arek** [comment] 2020-01-08 19:09
Thanks! 
There remains issue, compilation error:
```
g++ -c -pipe -Wextra -Werror -O2 -std=c++1y -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I.. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebSockets -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o mainwindow.o mainwindow.cpp
In file included from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h:45:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmainwindow.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMainWindow:1,
                 from mainwindow.h:5,
                 from mainwindow.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h: In instantiation of ‘static typename std::enable_if<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == -1), QMetaObject::Connection>::type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, Func2) [with Func1 = void (Czateria::LoginSession::*)(); Func2 = MainWindow::startLogin(const Czateria::Room&)::<lambda()>; typename std::enable_if<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == -1), QMetaObject::Connection>::type = QMetaObject::Connection; typename QtPrivate::FunctionPointer<Func>::Object = Czateria::LoginSession]’:
mainwindow.cpp:220:21:   required from here
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:308:74: error: use of deleted function ‘MainWindow::startLogin(const Czateria::Room&)::<lambda()>::<lambda>(const MainWindow::startLogin(const Czateria::Room&)::<lambda()>&)’
         return connect(sender, signal, sender, slot, Qt::DirectConnection);
                                                                          ^
mainwindow.cpp:207:43: note: ‘MainWindow::startLogin(const Czateria::Room&)::<lambda()>::<lambda>(const MainWindow::startLogin(const Czateria::Room&)::<lambda()>&)’ is implicitly deleted because the default definition would be ill-formed:
                    [=, c = std::move(conn)]() {
                                           ^
mainwindow.cpp:207:43: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = QMetaObject::Connection; _Dp = std::default_delete<QMetaObject::Connection>]’
In file included from /usr/include/c++/7/memory:80:0,
                 from mainwindow.cpp:18:
/usr/include/c++/7/bits/unique_ptr.h:388:7: note: declared here
       unique_ptr(const unique_ptr&) = delete;
       ^~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h:45:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmainwindow.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMainWindow:1,
                 from mainwindow.h:5,
                 from mainwindow.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:314:13: note:   initializing argument 4 of ‘static typename std::enable_if<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == -1), QMetaObject::Connection>::type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const QObject*, Func2, Qt::ConnectionType) [with Func1 = void (Czateria::LoginSession::*)(); Func2 = MainWindow::startLogin(const Czateria::Room&)::<lambda()>; typename std::enable_if<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == -1), QMetaObject::Connection>::type = QMetaObject::Connection; typename QtPrivate::FunctionPointer<Func>::Object = Czateria::LoginSession]’
             connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal, const QObject *context, Func2 slot,
             ^~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:314:13: error: ‘static typename std::enable_if<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == -1), QMetaObject::Connection>::type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const QObject*, Func2, Qt::ConnectionType) [with Func1 = void (Czateria::LoginSession::*)(); Func2 = MainWindow::startLogin(const Czateria::Room&)::<lambda()>; typename std::enable_if<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == -1), QMetaObject::Connection>::type = QMetaObject::Connection; typename QtPrivate::FunctionPointer<Func>::Object = Czateria::LoginSession]’, declared using local type ‘MainWindow::startLogin(const Czateria::Room&)::<lambda()>’, is used but never defined [-fpermissive]
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:314:13: error: ‘static typename std::enable_if<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == -1), QMetaObject::Connection>::type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const QObject*, Func2, Qt::ConnectionType) [with Func1 = void (Czateria::LoginSession::*)(); Func2 = MainWindow::startLogin(const Czateria::Room&)::<lambda()>]’ used but never defined [-Werror]
```

**Comment by xavery** [comment] 2020-01-08 19:31
Weird - should work now, but I'm surprised as to why it didn't work with `unique_ptr`.

**Comment by Arek-Arek** [comment] 2020-01-08 19:38
Yeah, ubuntu 18 without additional repos.

**Comment by xavery** [comment] 2020-01-08 20:04
Okay, I changed the workflow files so builds now run with Qt 5.9.5, which is the version currently in the Ubuntu repos.

**Comment by Arek-Arek** [comment] 2020-01-10 08:55
Tested, reconnecting works for me.
